apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: unit-test
spec:
  workspaces:
    - name: source
  steps:
    - name: unit-test
      workingDir: $(workspaces.source.path)
      image: registry.cn-hangzhou.aliyuncs.com/coolops/golang:1.17.5
      env:
        - name: GOPROXY
          value: https://goproxy.cn
      command: ["go"]
      args:
        - "test"
        - "./..."
